window.BOOK_META = {
  title: "Arguments for An Abolishment of Corporate-Owned America",
  subtitle: "An Anarcho-Syndicalist Manifesto",
  author: "Alexander Caro",
  year: 2026,
  cta: "Buy the digital edition",
  headline: "The country is still called a republic. The owners are not voters.",
  blurb:
    "A 2026 manifesto on corporate rule, managed consent, and what a workers' republic would actually require. Digital edition $14.99.",
  who: "Written for readers who already suspect the two parties are staff, not rivals. If you want a candidate brochure, this is not it. If you want the argument laid out in order, it is.",
  what: "Six chapters. Empire cycle. Labor and revolt. School as sorting and screens as the new hall monitor. Domestic politics as theater. Foreign policy at the edge of a larger war. A close that names a direction: federated production, workers' councils, peaceful popular abolishment of corporate rule.",
  stance: "Not a call to violence.",
  epigraph: "The Earth is littered with the ruins of empires that once believed they were eternal.",
  epigraphBy: "Camille Paglia",
  price: "14.99",
  venmo: "Alexander-Caro-31",
  note: "ALEXANDER CARO BOOK",
  payhip: "https://payhip.com/buy?link=IoHdW",
  payhipPage: "https://payhip.com/b/IoHdW",
  toc: [
    { slug: "front", title: "Author's Note, Preface, Introduction", sample: true },
    { slug: "ch1", title: "250-Year Empire Theory", sample: true },
    { slug: "ch2", title: "Inevitable Proletarian Revolution", sample: false },
    { slug: "ch3", title: "Illusion of Education and Surveillance Capitalism", sample: false },
    { slug: "ch4", title: "Puppet Politicians, Freedom, and Domestic Affairs", sample: false },
    { slug: "ch5", title: "Foreign Policy and the Precipice of WWIII", sample: false },
    { slug: "conclusion", title: "Conclusion", sample: false },
  ],
};
