window.KING_META = {
  title: "Arguments for An Abolishment of Corporate-Owned America",
  subtitle: "An Anarcho-Syndicalist Manifesto",
  author: "Alexander Caro",
  year: 2026,
  cta: "Get your copy of a revolution",
  blurb:
    "Alexander Caro. UF computer science. Tampa Bay. Digital edition $12.99. Instant download.",
  epigraph: "The Earth is littered with the ruins of empires that once believed they were eternal.",
  epigraphBy: "Camille Paglia",
  price: "12.99",
  venmo: "Alexander-Caro-31",
  note: "ALEXANDER CARO BOOK",
  payhip: "https://payhip.com/buy?link=IoHdW",
  payhipPage: "https://payhip.com/b/IoHdW",
  toc: [
    { slug: "front", title: "Author's Note, Preface, Introduction", sample: true },
    { slug: "ch1", title: "250-Year Empire Theory", sample: false },
    { slug: "ch2", title: "Inevitable Proletarian Revolution", sample: false },
    { slug: "ch3", title: "Illusion of Education and Surveillance Capitalism", sample: false },
    { slug: "ch4", title: "Puppet Politicians, Freedom, and Domestic Affairs", sample: false },
    { slug: "ch5", title: "Foreign Policy and the Precipice of WWIII", sample: false },
    { slug: "conclusion", title: "Conclusion", sample: false },
  ],
};
